apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-scan-controller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - name: manager
        image: ParthLukhi/cluster-scan-controller:latest
        command:
        - /manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      serviceAccountName: cluster-scan-sa
      volumes:
      - name: cert
        secret:
          secretName: webhook-server-cert
