apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cluster-scan-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["scans.mydomain.com"]
  resources: ["clusterscans"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["scans.mydomain.com"]
  resources: ["clusterscans/status"]
  verbs: ["get", "update", "patch"]
