apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterscans.scans.mydomain.com
spec:
  group: scans.mydomain.com
  names:
    kind: ClusterScan
    listKind: ClusterScanList
    plural: clusterscans
    singular: clusterscan
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                schedule:
                  type: string
                oneOff:
                  type: boolean
            status:
              type: object
              properties:
                lastRunTime:
                  type: string
                  format: date-time
                jobName:
                  type: string
